---
- name: Write a simple file with ansible
  hosts: all
  gather_facts: false
  tasks: 
    - name: Write file test.txt to temp directory
      ansible.builtin.lineinfile:
        path: /tmp/test.txt
        line: just some fast and simple text
        create: true